### ISSUE TITLE
Error: Cannot find module '@anush008/tokenizers-linux-x64-musl'

### ISSUE THREAD

**Issue by Madnex** [Anush008/tokenizers#1]
Hi! I wanted to try your fastembed implementation for javascript (working with strapi). However, it fails at the start already `const { EmbeddingModel, FlagEmbedding } = require("fastembed");`. Here is the stack:

```
| Error: Cannot find module '@anush008/tokenizers-linux-x64-musl'
strapi            | Require stack:
strapi            | - /opt/node_modules/@anush008/tokenizers/index.js
strapi            | - /opt/node_modules/fastembed/lib/cjs/fastembed.js
strapi            | - /opt/node_modules/fastembed/lib/cjs/index.js
```

I'm running this in a docker container based on node:18-alpine. I peeked at the [index.js ](https://github.com/Anush008/tokenizers/blob/main/index.js) file and saw that the `isMusl` check is for Node 10? What exactly is it checking? And why does the corresponding module not exist anymore? 

Thanks for your help! :)

**Comment by Anush008** [comment]
Hey @Madnex. This repository is my effort to build the Tokenizers Node bindings for multiple-platforms using GitHub Actions. I don't own the implementation. You can find the actual implementation here and raise an issue for clarification there.
https://github.com/huggingface/tokenizers/tree/main/bindings/node

**Comment by Madnex** [comment]
Oh okay, thanks!
